version: 2.1
jobs:
  node14:
    docker:
      - image: circleci/node:14
    steps:
      - test
commands:
  test:
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: unit test
          command: |
            yarn run ci:test
workflows:
  version: 2
  build_and_test:
    jobs:
      - node14
